### ISSUE TITLE
Cannot compile with the latest

### ISSUE THREAD

**Issue by pzoltowski** [AudioKit/SamplerDemo#6]
Couldn't compile with the latest pod AudioKit 4.11.2 using Xcode 12.1.
Got the following errors:
```
Swift Compiler Error Group
Unable to load standard library for target 'arm64-apple-ios10.0-simulator'
/Users/patryk/Developer/workspace/ios/playground/SamplerDemo-master/iOS/SamplerDemo/AKSampler+moreSFZ.swift:9:8: Failed to build module 'AudioKit' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced
```

**Comment by megastep** [comment]
Update your CocoaPods installation to the latest version (1.10 or later) and try again.

**Comment by pzoltowski** [comment]
Thanks this solved the above error but got another one - I guess some breaking changes between 4.5 and 4.11?
```

Swift Compiler Error Group
/Users/patryk/Developer/workspace/ios/playground/SamplerDemo-master-1/iOS/SamplerDemo/Conductor.swift:49:17: Module 'AudioKit' has no member named 'start'
/Users/patryk/Developer/workspace/ios/playground/SamplerDemo-master-1/iOS/SamplerDemo/Conductor.swift:47:9: Module 'AudioKit' has no member named 'output'
```

**Comment by megastep** [comment]
Yes, we had to rename the `AudioKit` class to `AKManager` to avoid conflicts with module names. Just update the class name in your code and you should be good to go.

**Comment by megastep** [comment]
I didn't realize this was a sample repo so I guess it is out of date. Advice still applies though.
